### ISSUE TITLE
Inaccurate example of sending JSON

### ISSUE THREAD

**Issue by bcho** [winterssy/sreq#1]
In the example:

```golang
data, err := sreq.
    Post("http://httpbin.org/post").
    JSON(sreq.Data{
        "msg": "hello world",
        "num": 2019,
    }).
    Send().
    Text()
if err != nil {
    panic(err)
}
fmt.Println(data)
```

But from the code, I think the `Post` call will create a `Response` instance and send the request (there is no `Send` method iin the Response type too).

Did I miss something? Thanks!

**Comment by winterssy** [comment]
`Post` just wraps your request option into a `Client`, `Send` does HTTP request indeed.
Furthermore, your code shows the old API of sreq, please make the same request by using the new API as follow.
```go
data, err := sreq.
	Post("http://httpbin.org/post",
		sreq.WithJSON(sreq.Data{
			"msg": "hello world",
			"num": 2019,
		}),
	).
	Text()
if err != nil {
	panic(err)
}
fmt.Println(data)
```
