### ISSUE TITLE
Not able to get resp data when using EnsureStatusOk

### ISSUE THREAD

**Issue by valpa** [winterssy/sreq#2]
Hi,

My use case is to get the response data (JSON data) regardless what the status code is.

I need to do something else on the resp data when the status code is not 200, so I use EnsureStatusOk(). But then I cannot get the response data.

`		data, err := sreq.Post("http://url/").
			EnsureStatusOk().
			H()`

How can I get response data with EnsureStatusOk(), or get the status code and data without using EnsureStatusOk()?

**Comment by winterssy** [comment]
You should not use `EnsureStatusOk` api if you want to access the JSON response regardless what the status code is. And you can get the status code by using `resp.RawResponse.StatusCode`. For example,
```go
resp := sreq.Post("http://url/")
rawResponse, err := resp.Raw()
if err != nil {
	panic(err)
}
if rawResponse.StatusCode == 200 {
	// response status code is 200
} else {
	// response status code is not 200
}
```
